services:
  nginx:
    image: nginx:1.25
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 50080:80
    depends_on:
      - php-fpm

  postgres:
    image: postgres:15.4
    ports:
      - 50032:5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PSQL_HISTORY=/var/lib/postgresql/history/postgres
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./data/postgres-psql-history:/var/lib/postgresql/history

  php-fpm:
    build: docker/php
    volumes:
      - .:/app
      - ./data/composer:/root/.composer
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./data/xdebug:/xdebug
    ports:
      - 9000
    env_file:
      - .env